FROM golang:1.13.4

RUN go get github.com/jinzhu/gorm  
RUN go get github.com/jinzhu/gorm/dialects/mysql
RUN go get github.com/gorilla/mux
RUN go get github.com/sk409/goconst
RUN go get github.com/sk409/gosession
RUN go get github.com/sk409/gogit

WORKDIR /go/src/github.com/sk409/sdso